baseURL = "https://stephenajulu5.netlify.app"
languageCode = "en-us"
paginate = 6
title = "Stephen Ajulu"
# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "About"
url = "#about"
weight = 2
[[menu.main]]
name = "Service"
url = "#service"
weight = 3
[[menu.main]]
name = "Work"
url = "#portfolio"
weight = 4
[[menu.main]]
name = "Resume"
url = "#resume"
weight = 5
[[menu.main]]
name = "Blog"
url = "#blog"
weight = 6
[[menu.main]]
name = "Contact"
url = "#contact"
weight = 7

# Sitemap Menu
[[menu.sitemap]]
name = "About me"
url = "about"
weight = 1
[[menu.sitemap]]
name = "Frequently Ask Question"
url = "faq"
weight = 2
[[menu.sitemap]]
name = "Privacy & Policy"
url = "privacy-policy"
weight = 3
[[menu.sitemap]]
name = "Latest Articles"
url = "#"
weight = 4

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "All right reserved copyright Â© Stephen Ajulu 2020"
footerLogo = "images/contact/widget-logo.png"
formspreeURL = "https://formspree.io/f/alunje73@gmail.com"
googleAnalytics = "UA-132349593-3"
logo = "images/site-navigation/logo.png"

[params.address]
address = "Nairobi, Kenya"
email = "alunje73gmail.com"
openingHours = "Call me between 10am and 6pm"
phone = "+254 726 024 219"

[params.map]
APIkey = "YOUR GOOGLE MAP API"
latitude = "23.7783741"
longitude = "90.3746808"
pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-facebook-official"
url = "https://www.facebook.com/stephenajulu"
weight = 1
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/in/stephenajulu"
weight = 2
[[params.social]]
icon = "fa-pinterest-square"
url = "https://www.pinterest.com/stephenajulu"
weight = 3
[[params.social]]
icon = "fa-twitter-square"
url = "https://twitter.com/stephenajulu"
weight = 4
